/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.stellarxraven17.rubylands.init;

import net.stellarxraven17.rubylands.block.YeahWeHadFunWithThisAsYouCanSeeBlock;
import net.stellarxraven17.rubylands.block.WoodenPillarBlock;
import net.stellarxraven17.rubylands.block.WarpedPillarBlock;
import net.stellarxraven17.rubylands.block.TileBlockBlock;
import net.stellarxraven17.rubylands.block.TileBlock4Block;
import net.stellarxraven17.rubylands.block.TileBlock3Block;
import net.stellarxraven17.rubylands.block.TileBlock2NonFuckedBlock;
import net.stellarxraven17.rubylands.block.TileBlock2Block;
import net.stellarxraven17.rubylands.block.TeaWoodBlock;
import net.stellarxraven17.rubylands.block.TeaTrapdoorBlock;
import net.stellarxraven17.rubylands.block.TeaStairsBlock;
import net.stellarxraven17.rubylands.block.TeaSlabBlock;
import net.stellarxraven17.rubylands.block.TeaSaplingBlock;
import net.stellarxraven17.rubylands.block.TeaPressurePlateBlock;
import net.stellarxraven17.rubylands.block.TeaPlanksBlock;
import net.stellarxraven17.rubylands.block.TeaLogBlock;
import net.stellarxraven17.rubylands.block.TeaLeavesBlock;
import net.stellarxraven17.rubylands.block.TeaFenceGateBlock;
import net.stellarxraven17.rubylands.block.TeaFenceBlock;
import net.stellarxraven17.rubylands.block.TeaDoorBlock;
import net.stellarxraven17.rubylands.block.TeaButtonBlock;
import net.stellarxraven17.rubylands.block.StrippedTeaWoodBlock;
import net.stellarxraven17.rubylands.block.StrippedTeaLogBlock;
import net.stellarxraven17.rubylands.block.StrippedFlamewoodWoodBlock;
import net.stellarxraven17.rubylands.block.StrippedFlamewoodLogBlock;
import net.stellarxraven17.rubylands.block.StonePathBlock;
import net.stellarxraven17.rubylands.block.SprucePillarBlock;
import net.stellarxraven17.rubylands.block.SaltBricksWallBlock;
import net.stellarxraven17.rubylands.block.SaltBricksStairsBlock;
import net.stellarxraven17.rubylands.block.SaltBricksSlabBlock;
import net.stellarxraven17.rubylands.block.SaltBricksBlock;
import net.stellarxraven17.rubylands.block.SaltBlockBlock;
import net.stellarxraven17.rubylands.block.PyriteOreBlock;
import net.stellarxraven17.rubylands.block.PyriteBlockBlock;
import net.stellarxraven17.rubylands.block.PolishedLowStoneBlock;
import net.stellarxraven17.rubylands.block.PetrifiedWoodBlock;
import net.stellarxraven17.rubylands.block.ObsidianBrickBlock;
import net.stellarxraven17.rubylands.block.MyconWoodBlock;
import net.stellarxraven17.rubylands.block.MyconStairsBlock;
import net.stellarxraven17.rubylands.block.MyconSlabBlock;
import net.stellarxraven17.rubylands.block.MyconPressurePlateBlock;
import net.stellarxraven17.rubylands.block.MyconPlanksBlock;
import net.stellarxraven17.rubylands.block.MyconLogBlock;
import net.stellarxraven17.rubylands.block.MyconLeavesBlock;
import net.stellarxraven17.rubylands.block.MyconFenceGateBlock;
import net.stellarxraven17.rubylands.block.MyconFenceBlock;
import net.stellarxraven17.rubylands.block.MyconButtonBlock;
import net.stellarxraven17.rubylands.block.MalachiteOreBlock;
import net.stellarxraven17.rubylands.block.MalachiteBlockBlock;
import net.stellarxraven17.rubylands.block.LowStoneMalachiteOreBlock;
import net.stellarxraven17.rubylands.block.LowStoneLaceAgateOreBlock;
import net.stellarxraven17.rubylands.block.LowStoneGoldOreBlock;
import net.stellarxraven17.rubylands.block.LowStoneDiamondOreBlock;
import net.stellarxraven17.rubylands.block.LowStoneBricksBlock;
import net.stellarxraven17.rubylands.block.LowStoneBlock;
import net.stellarxraven17.rubylands.block.LowPyriteOreBlock;
import net.stellarxraven17.rubylands.block.LowClinohumiteOreBlock;
import net.stellarxraven17.rubylands.block.LaceAgateOreBlock;
import net.stellarxraven17.rubylands.block.LaceAgateBlockBlock;
import net.stellarxraven17.rubylands.block.JunglePillarBlock;
import net.stellarxraven17.rubylands.block.IronLowStoneOreBlock;
import net.stellarxraven17.rubylands.block.IronBrickBlock;
import net.stellarxraven17.rubylands.block.Imgur9F0A3unBlock;
import net.stellarxraven17.rubylands.block.IceDoorBlock;
import net.stellarxraven17.rubylands.block.HubDoorBlock;
import net.stellarxraven17.rubylands.block.HardenedCactusStemBlock;
import net.stellarxraven17.rubylands.block.HardenedCactusArmBlock;
import net.stellarxraven17.rubylands.block.GreenstoneBrickBlock;
import net.stellarxraven17.rubylands.block.GoldenFlowerInfGoldBlock;
import net.stellarxraven17.rubylands.block.GoldBrickBlock;
import net.stellarxraven17.rubylands.block.GlowingFlowerInfObsidianBlock;
import net.stellarxraven17.rubylands.block.GlowingFlowerInfBasicBlock;
import net.stellarxraven17.rubylands.block.GlowingFlowerBlock;
import net.stellarxraven17.rubylands.block.FreezerBlock;
import net.stellarxraven17.rubylands.block.FortifiedGlassBlock;
import net.stellarxraven17.rubylands.block.FlamewoodWoodBlock;
import net.stellarxraven17.rubylands.block.FlamewoodTrapdoorBlock;
import net.stellarxraven17.rubylands.block.FlamewoodStairsBlock;
import net.stellarxraven17.rubylands.block.FlamewoodSlabBlock;
import net.stellarxraven17.rubylands.block.FlamewoodSaplingBlock;
import net.stellarxraven17.rubylands.block.FlamewoodPressurePlateBlock;
import net.stellarxraven17.rubylands.block.FlamewoodPlanksBlock;
import net.stellarxraven17.rubylands.block.FlamewoodPillarBlock;
import net.stellarxraven17.rubylands.block.FlamewoodLogBlock;
import net.stellarxraven17.rubylands.block.FlamewoodLeavesBlock;
import net.stellarxraven17.rubylands.block.FlamewoodFenceGateBlock;
import net.stellarxraven17.rubylands.block.FlamewoodFenceBlock;
import net.stellarxraven17.rubylands.block.FlamewoodDoorBlock;
import net.stellarxraven17.rubylands.block.FlamewoodButtonBlock;
import net.stellarxraven17.rubylands.block.EssenceTransformerBlock;
import net.stellarxraven17.rubylands.block.EssenceCacheBlock;
import net.stellarxraven17.rubylands.block.ElderMyceliumBlock;
import net.stellarxraven17.rubylands.block.ElderLilyBlock;
import net.stellarxraven17.rubylands.block.DimensionWallBlockBlock;
import net.stellarxraven17.rubylands.block.DimensionFloorBlockBlock;
import net.stellarxraven17.rubylands.block.DiamondBrickBlock;
import net.stellarxraven17.rubylands.block.DeepslatePyriteOreBlock;
import net.stellarxraven17.rubylands.block.DeepslateMalachiteOreBlock;
import net.stellarxraven17.rubylands.block.DeepslateLaceAgateOreBlock;
import net.stellarxraven17.rubylands.block.DeepslateClinohumiteOreBlock;
import net.stellarxraven17.rubylands.block.DebugBlock;
import net.stellarxraven17.rubylands.block.DarkOakPillarBlock;
import net.stellarxraven17.rubylands.block.CrimsonPillarBlock;
import net.stellarxraven17.rubylands.block.CrackedLowStoneBricksBlock;
import net.stellarxraven17.rubylands.block.CobbledLowStoneBlock;
import net.stellarxraven17.rubylands.block.CoalLowStoneOreBlock;
import net.stellarxraven17.rubylands.block.ClinohumiteOreBlock;
import net.stellarxraven17.rubylands.block.ClinohumiteBlockBlock;
import net.stellarxraven17.rubylands.block.CherryPillarBlock;
import net.stellarxraven17.rubylands.block.CactusStairsBlock;
import net.stellarxraven17.rubylands.block.CactusSlabBlock;
import net.stellarxraven17.rubylands.block.CactusPressurePlateBlock;
import net.stellarxraven17.rubylands.block.CactusPlanksBlock;
import net.stellarxraven17.rubylands.block.CactusFenceGateBlock;
import net.stellarxraven17.rubylands.block.CactusFenceBlock;
import net.stellarxraven17.rubylands.block.CactusButtonBlock;
import net.stellarxraven17.rubylands.block.BlueFireIdkBlock;
import net.stellarxraven17.rubylands.block.BirchPillarBlock;
import net.stellarxraven17.rubylands.block.BambooPillarBlock;
import net.stellarxraven17.rubylands.block.AltMojangHypostasisAnemoBlock;
import net.stellarxraven17.rubylands.block.AcaciaPillarBlock;
import net.stellarxraven17.rubylands.RdMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

public class RdModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(RdMod.MODID);
	public static final DeferredBlock<Block> OAK_PILLAR = REGISTRY.register("oak_pillar", WoodenPillarBlock::new);
	public static final DeferredBlock<Block> ESSENCE_CACHE = REGISTRY.register("essence_cache", EssenceCacheBlock::new);
	public static final DeferredBlock<Block> WINDOW = REGISTRY.register("window", FortifiedGlassBlock::new);
	public static final DeferredBlock<Block> IRON_BRICK = REGISTRY.register("iron_brick", IronBrickBlock::new);
	public static final DeferredBlock<Block> GOLD_BRICK = REGISTRY.register("gold_brick", GoldBrickBlock::new);
	public static final DeferredBlock<Block> DIAMOND_BRICK = REGISTRY.register("diamond_brick", DiamondBrickBlock::new);
	public static final DeferredBlock<Block> OBSIDIAN_BRICK = REGISTRY.register("obsidian_brick", ObsidianBrickBlock::new);
	public static final DeferredBlock<Block> STONE_SCAFFOLD = REGISTRY.register("stone_scaffold", TileBlockBlock::new);
	public static final DeferredBlock<Block> XRAY_SCAFFOLD = REGISTRY.register("xray_scaffold", TileBlock2Block::new);
	public static final DeferredBlock<Block> SCAFFOLD = REGISTRY.register("scaffold", TileBlock2NonFuckedBlock::new);
	public static final DeferredBlock<Block> BLUE_DIMENSION_TILE = REGISTRY.register("blue_dimension_tile", TileBlock3Block::new);
	public static final DeferredBlock<Block> YELLOW_DIMENSION_TILE = REGISTRY.register("yellow_dimension_tile", TileBlock4Block::new);
	public static final DeferredBlock<Block> DIMENSION_FLOOR = REGISTRY.register("dimension_floor", DimensionFloorBlockBlock::new);
	public static final DeferredBlock<Block> BLUE_FIRE_IDK = REGISTRY.register("blue_fire_idk", BlueFireIdkBlock::new);
	public static final DeferredBlock<Block> FLAME_INFUSED_LILY = REGISTRY.register("flame_infused_lily", GlowingFlowerInfBasicBlock::new);
	public static final DeferredBlock<Block> GOLD_INFUSED_LILY = REGISTRY.register("gold_infused_lily", GoldenFlowerInfGoldBlock::new);
	public static final DeferredBlock<Block> OBSIDIAN_INFUSED_LILY = REGISTRY.register("obsidian_infused_lily", GlowingFlowerInfObsidianBlock::new);
	public static final DeferredBlock<Block> SALT_BLOCK = REGISTRY.register("salt_block", SaltBlockBlock::new);
	public static final DeferredBlock<Block> DIMENSION_WALL = REGISTRY.register("dimension_wall", DimensionWallBlockBlock::new);
	public static final DeferredBlock<Block> CYAN_MOJANG_BLOCK = REGISTRY.register("cyan_mojang_block", AltMojangHypostasisAnemoBlock::new);
	public static final DeferredBlock<Block> WHITE_MOJANG_BLOCK = REGISTRY.register("white_mojang_block", Imgur9F0A3unBlock::new);
	public static final DeferredBlock<Block> GREEN_MOJANG_BLOCK = REGISTRY.register("green_mojang_block", YeahWeHadFunWithThisAsYouCanSeeBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_WOOD = REGISTRY.register("flamewood_wood", FlamewoodWoodBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_LOG = REGISTRY.register("flamewood_log", FlamewoodLogBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_PLANKS = REGISTRY.register("flamewood_planks", FlamewoodPlanksBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_LEAVES = REGISTRY.register("flamewood_leaves", FlamewoodLeavesBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_STAIRS = REGISTRY.register("flamewood_stairs", FlamewoodStairsBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_SLAB = REGISTRY.register("flamewood_slab", FlamewoodSlabBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_FENCE = REGISTRY.register("flamewood_fence", FlamewoodFenceBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_FENCE_GATE = REGISTRY.register("flamewood_fence_gate", FlamewoodFenceGateBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_PRESSURE_PLATE = REGISTRY.register("flamewood_pressure_plate", FlamewoodPressurePlateBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_BUTTON = REGISTRY.register("flamewood_button", FlamewoodButtonBlock::new);
	public static final DeferredBlock<Block> STRIPPED_FLAMEWOOD_LOG = REGISTRY.register("stripped_flamewood_log", StrippedFlamewoodLogBlock::new);
	public static final DeferredBlock<Block> STRIPPED_FLAMEWOOD_WOOD = REGISTRY.register("stripped_flamewood_wood", StrippedFlamewoodWoodBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_SAPLING = REGISTRY.register("flamewood_sapling", FlamewoodSaplingBlock::new);
	public static final DeferredBlock<Block> HUB_DOOR = REGISTRY.register("hub_door", HubDoorBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_DOOR = REGISTRY.register("flamewood_door", FlamewoodDoorBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_TRAPDOOR = REGISTRY.register("flamewood_trapdoor", FlamewoodTrapdoorBlock::new);
	public static final DeferredBlock<Block> STONE_PATH = REGISTRY.register("stone_path", StonePathBlock::new);
	public static final DeferredBlock<Block> SALT_BRICKS = REGISTRY.register("salt_bricks", SaltBricksBlock::new);
	public static final DeferredBlock<Block> SALT_BRICK_SLAB = REGISTRY.register("salt_brick_slab", SaltBricksSlabBlock::new);
	public static final DeferredBlock<Block> SALT_BRICK_STAIRS = REGISTRY.register("salt_brick_stairs", SaltBricksStairsBlock::new);
	public static final DeferredBlock<Block> SALT_BRICK_WALL = REGISTRY.register("salt_brick_wall", SaltBricksWallBlock::new);
	public static final DeferredBlock<Block> TEA_WOOD = REGISTRY.register("tea_wood", TeaWoodBlock::new);
	public static final DeferredBlock<Block> TEA_LOG = REGISTRY.register("tea_log", TeaLogBlock::new);
	public static final DeferredBlock<Block> TEA_PLANKS = REGISTRY.register("tea_planks", TeaPlanksBlock::new);
	public static final DeferredBlock<Block> TEA_LEAVES = REGISTRY.register("tea_leaves", TeaLeavesBlock::new);
	public static final DeferredBlock<Block> TEA_STAIRS = REGISTRY.register("tea_stairs", TeaStairsBlock::new);
	public static final DeferredBlock<Block> TEA_SLAB = REGISTRY.register("tea_slab", TeaSlabBlock::new);
	public static final DeferredBlock<Block> TEA_FENCE = REGISTRY.register("tea_fence", TeaFenceBlock::new);
	public static final DeferredBlock<Block> TEA_FENCE_GATE = REGISTRY.register("tea_fence_gate", TeaFenceGateBlock::new);
	public static final DeferredBlock<Block> TEA_PRESSURE_PLATE = REGISTRY.register("tea_pressure_plate", TeaPressurePlateBlock::new);
	public static final DeferredBlock<Block> TEA_BUTTON = REGISTRY.register("tea_button", TeaButtonBlock::new);
	public static final DeferredBlock<Block> TEA_DOOR = REGISTRY.register("tea_door", TeaDoorBlock::new);
	public static final DeferredBlock<Block> TEA_TRAPDOOR = REGISTRY.register("tea_trapdoor", TeaTrapdoorBlock::new);
	public static final DeferredBlock<Block> STRIPPED_TEA_WOOD = REGISTRY.register("stripped_tea_wood", StrippedTeaWoodBlock::new);
	public static final DeferredBlock<Block> STRIPPED_TEA_LOG = REGISTRY.register("stripped_tea_log", StrippedTeaLogBlock::new);
	public static final DeferredBlock<Block> TEA_SAPLING = REGISTRY.register("tea_sapling", TeaSaplingBlock::new);
	public static final DeferredBlock<Block> LOW_STONE = REGISTRY.register("low_stone", LowStoneBlock::new);
	public static final DeferredBlock<Block> COBBLED_LOW_STONE = REGISTRY.register("cobbled_low_stone", CobbledLowStoneBlock::new);
	public static final DeferredBlock<Block> ELDERSTONE_COAL_ORE = REGISTRY.register("elderstone_coal_ore", CoalLowStoneOreBlock::new);
	public static final DeferredBlock<Block> LOW_STONE_IRON_ORE = REGISTRY.register("low_stone_iron_ore", IronLowStoneOreBlock::new);
	public static final DeferredBlock<Block> LOW_STONE_GOLD_ORE = REGISTRY.register("low_stone_gold_ore", LowStoneGoldOreBlock::new);
	public static final DeferredBlock<Block> LOW_STONE_DIAMOND_ORE = REGISTRY.register("low_stone_diamond_ore", LowStoneDiamondOreBlock::new);
	public static final DeferredBlock<Block> MYCON_HYPHAE = REGISTRY.register("mycon_hyphae", MyconWoodBlock::new);
	public static final DeferredBlock<Block> MYCON_STEM = REGISTRY.register("mycon_stem", MyconLogBlock::new);
	public static final DeferredBlock<Block> MYCON_PLANKS = REGISTRY.register("mycon_planks", MyconPlanksBlock::new);
	public static final DeferredBlock<Block> MYCON_CAP = REGISTRY.register("mycon_cap", MyconLeavesBlock::new);
	public static final DeferredBlock<Block> MYCON_STAIRS = REGISTRY.register("mycon_stairs", MyconStairsBlock::new);
	public static final DeferredBlock<Block> MYCON_SLAB = REGISTRY.register("mycon_slab", MyconSlabBlock::new);
	public static final DeferredBlock<Block> MYCON_FENCE = REGISTRY.register("mycon_fence", MyconFenceBlock::new);
	public static final DeferredBlock<Block> MYCON_FENCE_GATE = REGISTRY.register("mycon_fence_gate", MyconFenceGateBlock::new);
	public static final DeferredBlock<Block> MYCON_PRESSURE_PLATE = REGISTRY.register("mycon_pressure_plate", MyconPressurePlateBlock::new);
	public static final DeferredBlock<Block> MYCON_BUTTON = REGISTRY.register("mycon_button", MyconButtonBlock::new);
	public static final DeferredBlock<Block> POLISHED_LOW_STONE = REGISTRY.register("polished_low_stone", PolishedLowStoneBlock::new);
	public static final DeferredBlock<Block> LOW_STONE_BRICKS = REGISTRY.register("low_stone_bricks", LowStoneBricksBlock::new);
	public static final DeferredBlock<Block> CRACKED_LOW_STONE_BRICKS = REGISTRY.register("cracked_low_stone_bricks", CrackedLowStoneBricksBlock::new);
	public static final DeferredBlock<Block> PYRITE_ORE = REGISTRY.register("pyrite_ore", PyriteOreBlock::new);
	public static final DeferredBlock<Block> PYRITE_BLOCK = REGISTRY.register("pyrite_block", PyriteBlockBlock::new);
	public static final DeferredBlock<Block> CLINOHUMITE_ORE = REGISTRY.register("clinohumite_ore", ClinohumiteOreBlock::new);
	public static final DeferredBlock<Block> CLINOHUMITE_BLOCK = REGISTRY.register("clinohumite_block", ClinohumiteBlockBlock::new);
	public static final DeferredBlock<Block> LACE_AGATE_ORE = REGISTRY.register("lace_agate_ore", LaceAgateOreBlock::new);
	public static final DeferredBlock<Block> LACE_AGATE_BLOCK = REGISTRY.register("lace_agate_block", LaceAgateBlockBlock::new);
	public static final DeferredBlock<Block> MALACHITE_ORE = REGISTRY.register("malachite_ore", MalachiteOreBlock::new);
	public static final DeferredBlock<Block> MALACHITE_BLOCK = REGISTRY.register("malachite_block", MalachiteBlockBlock::new);
	public static final DeferredBlock<Block> LOW_MYCELIUM = REGISTRY.register("low_mycelium", ElderMyceliumBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_LACE_AGATE_ORE = REGISTRY.register("deepslate_lace_agate_ore", DeepslateLaceAgateOreBlock::new);
	public static final DeferredBlock<Block> LOW_LACE_AGATE_ORE = REGISTRY.register("low_lace_agate_ore", LowStoneLaceAgateOreBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_MALACHITE_ORE = REGISTRY.register("deepslate_malachite_ore", DeepslateMalachiteOreBlock::new);
	public static final DeferredBlock<Block> LOW_MALACHITE_ORE = REGISTRY.register("low_malachite_ore", LowStoneMalachiteOreBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_PYRITE_ORE = REGISTRY.register("deepslate_pyrite_ore", DeepslatePyriteOreBlock::new);
	public static final DeferredBlock<Block> LOW_PYRITE_ORE = REGISTRY.register("low_pyrite_ore", LowPyriteOreBlock::new);
	public static final DeferredBlock<Block> DEEPSLATE_CLINOHUMITE_ORE = REGISTRY.register("deepslate_clinohumite_ore", DeepslateClinohumiteOreBlock::new);
	public static final DeferredBlock<Block> LOW_CLINOHUMITE_ORE = REGISTRY.register("low_clinohumite_ore", LowClinohumiteOreBlock::new);
	public static final DeferredBlock<Block> PETRIFIED_WOOD = REGISTRY.register("petrified_wood", PetrifiedWoodBlock::new);
	public static final DeferredBlock<Block> ESSENCE_TRANSFORMER = REGISTRY.register("essence_transformer", EssenceTransformerBlock::new);
	public static final DeferredBlock<Block> SPRUCE_PILLAR = REGISTRY.register("spruce_pillar", SprucePillarBlock::new);
	public static final DeferredBlock<Block> BIRCH_PILLAR = REGISTRY.register("birch_pillar", BirchPillarBlock::new);
	public static final DeferredBlock<Block> JUNGLE_PILLAR = REGISTRY.register("jungle_pillar", JunglePillarBlock::new);
	public static final DeferredBlock<Block> ACACIA_PILLAR = REGISTRY.register("acacia_pillar", AcaciaPillarBlock::new);
	public static final DeferredBlock<Block> DARK_OAK_PILLAR = REGISTRY.register("dark_oak_pillar", DarkOakPillarBlock::new);
	public static final DeferredBlock<Block> CRIMSON_PILLAR = REGISTRY.register("crimson_pillar", CrimsonPillarBlock::new);
	public static final DeferredBlock<Block> WARPED_PILLAR = REGISTRY.register("warped_pillar", WarpedPillarBlock::new);
	public static final DeferredBlock<Block> FLAMEWOOD_PILLAR = REGISTRY.register("flamewood_pillar", FlamewoodPillarBlock::new);
	public static final DeferredBlock<Block> CACTUS_PLANKS = REGISTRY.register("cactus_planks", CactusPlanksBlock::new);
	public static final DeferredBlock<Block> CACTUS_STAIRS = REGISTRY.register("cactus_stairs", CactusStairsBlock::new);
	public static final DeferredBlock<Block> CACTUS_SLAB = REGISTRY.register("cactus_slab", CactusSlabBlock::new);
	public static final DeferredBlock<Block> CACTUS_FENCE = REGISTRY.register("cactus_fence", CactusFenceBlock::new);
	public static final DeferredBlock<Block> CACTUS_FENCE_GATE = REGISTRY.register("cactus_fence_gate", CactusFenceGateBlock::new);
	public static final DeferredBlock<Block> CACTUS_PRESSURE_PLATE = REGISTRY.register("cactus_pressure_plate", CactusPressurePlateBlock::new);
	public static final DeferredBlock<Block> CACTUS_BUTTON = REGISTRY.register("cactus_button", CactusButtonBlock::new);
	public static final DeferredBlock<Block> HARDENED_CACTUS_STEM = REGISTRY.register("hardened_cactus_stem", HardenedCactusStemBlock::new);
	public static final DeferredBlock<Block> HARDENED_CACTUS_ARM = REGISTRY.register("hardened_cactus_arm", HardenedCactusArmBlock::new);
	public static final DeferredBlock<Block> LOW_LILY = REGISTRY.register("low_lily", ElderLilyBlock::new);
	public static final DeferredBlock<Block> GREENSTONE_BRICK = REGISTRY.register("greenstone_brick", GreenstoneBrickBlock::new);
	public static final DeferredBlock<Block> CHERRY_PILLAR = REGISTRY.register("cherry_pillar", CherryPillarBlock::new);
	public static final DeferredBlock<Block> WATER_LILY = REGISTRY.register("water_lily", GlowingFlowerBlock::new);
	public static final DeferredBlock<Block> DEBUG = REGISTRY.register("debug", DebugBlock::new);
	public static final DeferredBlock<Block> BAMBOO_PILLAR = REGISTRY.register("bamboo_pillar", BambooPillarBlock::new);
	public static final DeferredBlock<Block> ICE_DOOR = REGISTRY.register("ice_door", IceDoorBlock::new);
	public static final DeferredBlock<Block> FREEZER = REGISTRY.register("freezer", FreezerBlock::new);

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@EventBusSubscriber(bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			StonePathBlock.blockColorLoad(event);
			TeaLeavesBlock.blockColorLoad(event);
		}
	}
}