/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.fauxjang.rubylands.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import com.fauxjang.rubylands.item.*;
import com.fauxjang.rubylands.RdMod;

public class RdModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(RdMod.MODID);
	public static final DeferredItem<Item> ESSENCE;
	public static final DeferredItem<Item> OAK_PILLAR;
	public static final DeferredItem<Item> ESSENCE_CACHE;
	public static final DeferredItem<Item> OBSIDIAN_INGOT;
	public static final DeferredItem<Item> OBSERVER_FUR;
	public static final DeferredItem<Item> WINDOW;
	public static final DeferredItem<Item> IRON_BRICK;
	public static final DeferredItem<Item> GOLD_BRICK;
	public static final DeferredItem<Item> DIAMOND_BRICK;
	public static final DeferredItem<Item> OBSIDIAN_BRICK;
	public static final DeferredItem<Item> STONE_SCAFFOLD;
	public static final DeferredItem<Item> XRAY_SCAFFOLD;
	public static final DeferredItem<Item> SCAFFOLD;
	public static final DeferredItem<Item> BLUE_DIMENSION_TILE;
	public static final DeferredItem<Item> YELLOW_DIMENSION_TILE;
	public static final DeferredItem<Item> DIMENSION_FLOOR;
	public static final DeferredItem<Item> BLUE_FIRE_IDK;
	public static final DeferredItem<Item> FLAME_INFUSED_LILY;
	public static final DeferredItem<Item> GOLD_INFUSED_LILY;
	public static final DeferredItem<Item> OBSIDIAN_INFUSED_LILY;
	public static final DeferredItem<Item> SALT_BLOCK;
	public static final DeferredItem<Item> DIMENSION_WALL;
	public static final DeferredItem<Item> OBSERVER_SPAWN_EGG;
	public static final DeferredItem<Item> CYAN_MOJANG_BLOCK;
	public static final DeferredItem<Item> WHITE_MOJANG_BLOCK;
	public static final DeferredItem<Item> GREEN_MOJANG_BLOCK;
	public static final DeferredItem<Item> FLAMEWOOD_WOOD;
	public static final DeferredItem<Item> FLAMEWOOD_LOG;
	public static final DeferredItem<Item> FLAMEWOOD_PLANKS;
	public static final DeferredItem<Item> FLAMEWOOD_LEAVES;
	public static final DeferredItem<Item> FLAMEWOOD_STAIRS;
	public static final DeferredItem<Item> FLAMEWOOD_SLAB;
	public static final DeferredItem<Item> FLAMEWOOD_FENCE;
	public static final DeferredItem<Item> FLAMEWOOD_FENCE_GATE;
	public static final DeferredItem<Item> FLAMEWOOD_PRESSURE_PLATE;
	public static final DeferredItem<Item> FLAMEWOOD_BUTTON;
	public static final DeferredItem<Item> STRIPPED_FLAMEWOOD_LOG;
	public static final DeferredItem<Item> STRIPPED_FLAMEWOOD_WOOD;
	public static final DeferredItem<Item> OBSIDIAN_HELMET;
	public static final DeferredItem<Item> OBSIDIAN_CHESTPLATE;
	public static final DeferredItem<Item> OBSIDIAN_LEGGINGS;
	public static final DeferredItem<Item> OBSIDIAN_BOOTS;
	public static final DeferredItem<Item> FLAMEWOOD_SAPLING;
	public static final DeferredItem<Item> HUB_DOOR;
	public static final DeferredItem<Item> FLAMEWOOD_DOOR;
	public static final DeferredItem<Item> FLAMEWOOD_TRAPDOOR;
	public static final DeferredItem<Item> STONE_PATH;
	public static final DeferredItem<Item> SALT_BRICKS;
	public static final DeferredItem<Item> SALT_BRICK_SLAB;
	public static final DeferredItem<Item> SALT_BRICK_STAIRS;
	public static final DeferredItem<Item> SALT_BRICK_WALL;
	public static final DeferredItem<Item> ROCK_BEETLE;
	public static final DeferredItem<Item> OBSIDIAN_SWORD;
	public static final DeferredItem<Item> OBSIDIAN_PICKAXE;
	public static final DeferredItem<Item> OBSIDIAN_AXE;
	public static final DeferredItem<Item> OBSIDIAN_SHOVEL;
	public static final DeferredItem<Item> OBSIDIAN_HOE;
	public static final DeferredItem<Item> ESSENCE_RIFLE;
	public static final DeferredItem<Item> TEA_WOOD;
	public static final DeferredItem<Item> TEA_LOG;
	public static final DeferredItem<Item> TEA_PLANKS;
	public static final DeferredItem<Item> TEA_LEAVES;
	public static final DeferredItem<Item> TEA_STAIRS;
	public static final DeferredItem<Item> TEA_SLAB;
	public static final DeferredItem<Item> TEA_FENCE;
	public static final DeferredItem<Item> TEA_FENCE_GATE;
	public static final DeferredItem<Item> TEA_PRESSURE_PLATE;
	public static final DeferredItem<Item> TEA_BUTTON;
	public static final DeferredItem<Item> TEA_DOOR;
	public static final DeferredItem<Item> TEA_TRAPDOOR;
	public static final DeferredItem<Item> STRIPPED_TEA_WOOD;
	public static final DeferredItem<Item> STRIPPED_TEA_LOG;
	public static final DeferredItem<Item> TEA_SAPLING;
	public static final DeferredItem<Item> LOW_STONE;
	public static final DeferredItem<Item> COBBLED_LOW_STONE;
	public static final DeferredItem<Item> ELDERSTONE_COAL_ORE;
	public static final DeferredItem<Item> LOW_STONE_IRON_ORE;
	public static final DeferredItem<Item> LOW_STONE_GOLD_ORE;
	public static final DeferredItem<Item> LOW_STONE_DIAMOND_ORE;
	public static final DeferredItem<Item> MYCON_HYPHAE;
	public static final DeferredItem<Item> MYCON_STEM;
	public static final DeferredItem<Item> MYCON_PLANKS;
	public static final DeferredItem<Item> MYCON_CAP;
	public static final DeferredItem<Item> MYCON_STAIRS;
	public static final DeferredItem<Item> MYCON_SLAB;
	public static final DeferredItem<Item> MYCON_FENCE;
	public static final DeferredItem<Item> MYCON_FENCE_GATE;
	public static final DeferredItem<Item> MYCON_PRESSURE_PLATE;
	public static final DeferredItem<Item> MYCON_BUTTON;
	public static final DeferredItem<Item> POLISHED_LOW_STONE;
	public static final DeferredItem<Item> LOW_STONE_BRICKS;
	public static final DeferredItem<Item> CRACKED_LOW_STONE_BRICKS;
	public static final DeferredItem<Item> PYRITE;
	public static final DeferredItem<Item> PYRITE_ORE;
	public static final DeferredItem<Item> PYRITE_BLOCK;
	public static final DeferredItem<Item> CLINOHUMITE;
	public static final DeferredItem<Item> CLINOHUMITE_ORE;
	public static final DeferredItem<Item> CLINOHUMITE_BLOCK;
	public static final DeferredItem<Item> LACE_AGATE;
	public static final DeferredItem<Item> LACE_AGATE_ORE;
	public static final DeferredItem<Item> LACE_AGATE_BLOCK;
	public static final DeferredItem<Item> MALACHITE;
	public static final DeferredItem<Item> MALACHITE_ORE;
	public static final DeferredItem<Item> MALACHITE_BLOCK;
	public static final DeferredItem<Item> LOW_MYCELIUM;
	public static final DeferredItem<Item> DEEPSLATE_LACE_AGATE_ORE;
	public static final DeferredItem<Item> LOW_LACE_AGATE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_MALACHITE_ORE;
	public static final DeferredItem<Item> LOW_MALACHITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_PYRITE_ORE;
	public static final DeferredItem<Item> LOW_PYRITE_ORE;
	public static final DeferredItem<Item> DEEPSLATE_CLINOHUMITE_ORE;
	public static final DeferredItem<Item> LOW_CLINOHUMITE_ORE;
	public static final DeferredItem<Item> PETRIFIED_WOOD;
	public static final DeferredItem<Item> ESSENCE_TRANSFORMER;
	public static final DeferredItem<Item> SPRUCE_PILLAR;
	public static final DeferredItem<Item> BIRCH_PILLAR;
	public static final DeferredItem<Item> JUNGLE_PILLAR;
	public static final DeferredItem<Item> ACACIA_PILLAR;
	public static final DeferredItem<Item> DARK_OAK_PILLAR;
	public static final DeferredItem<Item> CRIMSON_PILLAR;
	public static final DeferredItem<Item> WARPED_PILLAR;
	public static final DeferredItem<Item> FLAMEWOOD_PILLAR;
	public static final DeferredItem<Item> CACTUS_SWORD;
	public static final DeferredItem<Item> CACTUS_PLANKS;
	public static final DeferredItem<Item> CACTUS_STAIRS;
	public static final DeferredItem<Item> CACTUS_SLAB;
	public static final DeferredItem<Item> CACTUS_FENCE;
	public static final DeferredItem<Item> CACTUS_FENCE_GATE;
	public static final DeferredItem<Item> CACTUS_PRESSURE_PLATE;
	public static final DeferredItem<Item> CACTUS_BUTTON;
	public static final DeferredItem<Item> HARDENED_CACTUS_STEM;
	public static final DeferredItem<Item> HARDENED_CACTUS_ARM;
	public static final DeferredItem<Item> COPPER_NUGGET;
	public static final DeferredItem<Item> COPPER_SWORD;
	public static final DeferredItem<Item> COPPER_AXE;
	public static final DeferredItem<Item> COPPER_PICKAXE;
	public static final DeferredItem<Item> COPPER_SHOVEL;
	public static final DeferredItem<Item> COPPER_HOE;
	public static final DeferredItem<Item> LOW_LILY;
	public static final DeferredItem<Item> GREENSTONE_BRICK;
	public static final DeferredItem<Item> CHERRY_PILLAR;
	public static final DeferredItem<Item> WATER_LILY;
	public static final DeferredItem<Item> COPPER_HELMET;
	public static final DeferredItem<Item> COPPER_CHESTPLATE;
	public static final DeferredItem<Item> COPPER_LEGGINGS;
	public static final DeferredItem<Item> COPPER_BOOTS;
	public static final DeferredItem<Item> FRYSHROOM;
	public static final DeferredItem<Item> DEBUG;
	public static final DeferredItem<Item> APPLE_PIE;
	public static final DeferredItem<Item> BAMBOO_PILLAR;
	public static final DeferredItem<Item> ICE_DOOR;
	public static final DeferredItem<Item> FREEZER;
	public static final DeferredItem<Item> RAW_FLESH;
	public static final DeferredItem<Item> COOKED_FLESH;
	public static final DeferredItem<Item> MUSHROOM_PLANKS;
	public static final DeferredItem<Item> MUSHROOM_STAIRS;
	public static final DeferredItem<Item> MUSHROOM_SLAB;
	public static final DeferredItem<Item> MUSHROOM_FENCE;
	public static final DeferredItem<Item> MUSHROOM_FENCE_GATE;
	public static final DeferredItem<Item> MUSHROOM_PRESSURE_PLATE;
	public static final DeferredItem<Item> MUSHROOM_BUTTON;
	public static final DeferredItem<Item> SUGAR_COOKIE;
	public static final DeferredItem<Item> STRIPPED_MYCON_STEM;
	public static final DeferredItem<Item> STRIPPED_MYCON_HYPHAE;
	public static final DeferredItem<Item> FAKE_DIRT;
	public static final DeferredItem<Item> FAKE_GRASS;
	public static final DeferredItem<Item> HIGHWOOD_LOG;
	public static final DeferredItem<Item> HIGHWOOD_WOOD;
	public static final DeferredItem<Item> STRIPPED_HIGHWOOD_LOG;
	public static final DeferredItem<Item> STRIPPED_HIGHWOOD_WOOD;
	public static final DeferredItem<Item> HIGHWOOD_PLANKS;
	public static final DeferredItem<Item> HIGHWOOD_LEAVES;
	public static final DeferredItem<Item> HIGHWOOD_STAIRS;
	public static final DeferredItem<Item> HIGHWOOD_SLAB;
	public static final DeferredItem<Item> HIGHWOOD_FENCE;
	public static final DeferredItem<Item> HIGHWOOD_FENCE_GATE;
	public static final DeferredItem<Item> HIGHWOOD_DOOR;
	public static final DeferredItem<Item> HIGHWOOD_TRAPDOOR;
	public static final DeferredItem<Item> HIGHWOOD_PRESSURE_PLATE;
	public static final DeferredItem<Item> HIGHWOOD_BUTTON;
	static {
		ESSENCE = REGISTRY.register("essence", EssenceItem::new);
		OAK_PILLAR = block(RdModBlocks.OAK_PILLAR);
		ESSENCE_CACHE = block(RdModBlocks.ESSENCE_CACHE);
		OBSIDIAN_INGOT = REGISTRY.register("obsidian_ingot", ObsidianIngotItem::new);
		OBSERVER_FUR = REGISTRY.register("observer_fur", ObserverFurItem::new);
		WINDOW = block(RdModBlocks.WINDOW);
		IRON_BRICK = block(RdModBlocks.IRON_BRICK);
		GOLD_BRICK = block(RdModBlocks.GOLD_BRICK);
		DIAMOND_BRICK = block(RdModBlocks.DIAMOND_BRICK);
		OBSIDIAN_BRICK = block(RdModBlocks.OBSIDIAN_BRICK);
		STONE_SCAFFOLD = block(RdModBlocks.STONE_SCAFFOLD);
		XRAY_SCAFFOLD = block(RdModBlocks.XRAY_SCAFFOLD);
		SCAFFOLD = block(RdModBlocks.SCAFFOLD);
		BLUE_DIMENSION_TILE = block(RdModBlocks.BLUE_DIMENSION_TILE);
		YELLOW_DIMENSION_TILE = block(RdModBlocks.YELLOW_DIMENSION_TILE);
		DIMENSION_FLOOR = block(RdModBlocks.DIMENSION_FLOOR);
		BLUE_FIRE_IDK = block(RdModBlocks.BLUE_FIRE_IDK);
		FLAME_INFUSED_LILY = block(RdModBlocks.FLAME_INFUSED_LILY);
		GOLD_INFUSED_LILY = block(RdModBlocks.GOLD_INFUSED_LILY);
		OBSIDIAN_INFUSED_LILY = block(RdModBlocks.OBSIDIAN_INFUSED_LILY);
		SALT_BLOCK = block(RdModBlocks.SALT_BLOCK);
		DIMENSION_WALL = block(RdModBlocks.DIMENSION_WALL);
		OBSERVER_SPAWN_EGG = REGISTRY.register("observer_spawn_egg", () -> new DeferredSpawnEggItem(RdModEntities.OBSERVER, -8816263, -2041654, new Item.Properties()));
		CYAN_MOJANG_BLOCK = block(RdModBlocks.CYAN_MOJANG_BLOCK);
		WHITE_MOJANG_BLOCK = block(RdModBlocks.WHITE_MOJANG_BLOCK);
		GREEN_MOJANG_BLOCK = block(RdModBlocks.GREEN_MOJANG_BLOCK);
		FLAMEWOOD_WOOD = block(RdModBlocks.FLAMEWOOD_WOOD, new Item.Properties().fireResistant());
		FLAMEWOOD_LOG = block(RdModBlocks.FLAMEWOOD_LOG, new Item.Properties().fireResistant());
		FLAMEWOOD_PLANKS = block(RdModBlocks.FLAMEWOOD_PLANKS, new Item.Properties().fireResistant());
		FLAMEWOOD_LEAVES = block(RdModBlocks.FLAMEWOOD_LEAVES, new Item.Properties().fireResistant());
		FLAMEWOOD_STAIRS = block(RdModBlocks.FLAMEWOOD_STAIRS, new Item.Properties().fireResistant());
		FLAMEWOOD_SLAB = block(RdModBlocks.FLAMEWOOD_SLAB, new Item.Properties().fireResistant());
		FLAMEWOOD_FENCE = block(RdModBlocks.FLAMEWOOD_FENCE, new Item.Properties().fireResistant());
		FLAMEWOOD_FENCE_GATE = block(RdModBlocks.FLAMEWOOD_FENCE_GATE, new Item.Properties().fireResistant());
		FLAMEWOOD_PRESSURE_PLATE = block(RdModBlocks.FLAMEWOOD_PRESSURE_PLATE, new Item.Properties().fireResistant());
		FLAMEWOOD_BUTTON = block(RdModBlocks.FLAMEWOOD_BUTTON, new Item.Properties().fireResistant());
		STRIPPED_FLAMEWOOD_LOG = block(RdModBlocks.STRIPPED_FLAMEWOOD_LOG, new Item.Properties().fireResistant());
		STRIPPED_FLAMEWOOD_WOOD = block(RdModBlocks.STRIPPED_FLAMEWOOD_WOOD, new Item.Properties().fireResistant());
		OBSIDIAN_HELMET = REGISTRY.register("obsidian_helmet", ObsidianItem.Helmet::new);
		OBSIDIAN_CHESTPLATE = REGISTRY.register("obsidian_chestplate", ObsidianItem.Chestplate::new);
		OBSIDIAN_LEGGINGS = REGISTRY.register("obsidian_leggings", ObsidianItem.Leggings::new);
		OBSIDIAN_BOOTS = REGISTRY.register("obsidian_boots", ObsidianItem.Boots::new);
		FLAMEWOOD_SAPLING = block(RdModBlocks.FLAMEWOOD_SAPLING, new Item.Properties().fireResistant());
		HUB_DOOR = doubleBlock(RdModBlocks.HUB_DOOR, new Item.Properties().rarity(Rarity.UNCOMMON));
		FLAMEWOOD_DOOR = doubleBlock(RdModBlocks.FLAMEWOOD_DOOR, new Item.Properties().fireResistant());
		FLAMEWOOD_TRAPDOOR = block(RdModBlocks.FLAMEWOOD_TRAPDOOR, new Item.Properties().fireResistant());
		STONE_PATH = block(RdModBlocks.STONE_PATH);
		SALT_BRICKS = block(RdModBlocks.SALT_BRICKS);
		SALT_BRICK_SLAB = block(RdModBlocks.SALT_BRICK_SLAB);
		SALT_BRICK_STAIRS = block(RdModBlocks.SALT_BRICK_STAIRS);
		SALT_BRICK_WALL = block(RdModBlocks.SALT_BRICK_WALL);
		ROCK_BEETLE = REGISTRY.register("rock_beetle", RockBeetleItem::new);
		OBSIDIAN_SWORD = REGISTRY.register("obsidian_sword", ObsidianSwordItem::new);
		OBSIDIAN_PICKAXE = REGISTRY.register("obsidian_pickaxe", ObsidianPickaxeItem::new);
		OBSIDIAN_AXE = REGISTRY.register("obsidian_axe", ObsidianAxeItem::new);
		OBSIDIAN_SHOVEL = REGISTRY.register("obsidian_shovel", ObsidianShovelItem::new);
		OBSIDIAN_HOE = REGISTRY.register("obsidian_hoe", ObsidianHoeItem::new);
		ESSENCE_RIFLE = REGISTRY.register("essence_rifle", EssenceRifleItem::new);
		TEA_WOOD = block(RdModBlocks.TEA_WOOD);
		TEA_LOG = block(RdModBlocks.TEA_LOG);
		TEA_PLANKS = block(RdModBlocks.TEA_PLANKS);
		TEA_LEAVES = block(RdModBlocks.TEA_LEAVES);
		TEA_STAIRS = block(RdModBlocks.TEA_STAIRS);
		TEA_SLAB = block(RdModBlocks.TEA_SLAB);
		TEA_FENCE = block(RdModBlocks.TEA_FENCE);
		TEA_FENCE_GATE = block(RdModBlocks.TEA_FENCE_GATE);
		TEA_PRESSURE_PLATE = block(RdModBlocks.TEA_PRESSURE_PLATE);
		TEA_BUTTON = block(RdModBlocks.TEA_BUTTON);
		TEA_DOOR = doubleBlock(RdModBlocks.TEA_DOOR);
		TEA_TRAPDOOR = block(RdModBlocks.TEA_TRAPDOOR);
		STRIPPED_TEA_WOOD = block(RdModBlocks.STRIPPED_TEA_WOOD);
		STRIPPED_TEA_LOG = block(RdModBlocks.STRIPPED_TEA_LOG);
		TEA_SAPLING = block(RdModBlocks.TEA_SAPLING);
		LOW_STONE = block(RdModBlocks.LOW_STONE);
		COBBLED_LOW_STONE = block(RdModBlocks.COBBLED_LOW_STONE);
		ELDERSTONE_COAL_ORE = block(RdModBlocks.ELDERSTONE_COAL_ORE);
		LOW_STONE_IRON_ORE = block(RdModBlocks.LOW_STONE_IRON_ORE);
		LOW_STONE_GOLD_ORE = block(RdModBlocks.LOW_STONE_GOLD_ORE);
		LOW_STONE_DIAMOND_ORE = block(RdModBlocks.LOW_STONE_DIAMOND_ORE);
		MYCON_HYPHAE = block(RdModBlocks.MYCON_HYPHAE);
		MYCON_STEM = block(RdModBlocks.MYCON_STEM);
		MYCON_PLANKS = block(RdModBlocks.MYCON_PLANKS);
		MYCON_CAP = block(RdModBlocks.MYCON_CAP);
		MYCON_STAIRS = block(RdModBlocks.MYCON_STAIRS);
		MYCON_SLAB = block(RdModBlocks.MYCON_SLAB);
		MYCON_FENCE = block(RdModBlocks.MYCON_FENCE);
		MYCON_FENCE_GATE = block(RdModBlocks.MYCON_FENCE_GATE);
		MYCON_PRESSURE_PLATE = block(RdModBlocks.MYCON_PRESSURE_PLATE);
		MYCON_BUTTON = block(RdModBlocks.MYCON_BUTTON);
		POLISHED_LOW_STONE = block(RdModBlocks.POLISHED_LOW_STONE);
		LOW_STONE_BRICKS = block(RdModBlocks.LOW_STONE_BRICKS);
		CRACKED_LOW_STONE_BRICKS = block(RdModBlocks.CRACKED_LOW_STONE_BRICKS);
		PYRITE = REGISTRY.register("pyrite", PyriteItem::new);
		PYRITE_ORE = block(RdModBlocks.PYRITE_ORE);
		PYRITE_BLOCK = block(RdModBlocks.PYRITE_BLOCK);
		CLINOHUMITE = REGISTRY.register("clinohumite", ClinohumiteItem::new);
		CLINOHUMITE_ORE = block(RdModBlocks.CLINOHUMITE_ORE);
		CLINOHUMITE_BLOCK = block(RdModBlocks.CLINOHUMITE_BLOCK);
		LACE_AGATE = REGISTRY.register("lace_agate", LaceAgateItem::new);
		LACE_AGATE_ORE = block(RdModBlocks.LACE_AGATE_ORE);
		LACE_AGATE_BLOCK = block(RdModBlocks.LACE_AGATE_BLOCK);
		MALACHITE = REGISTRY.register("malachite", MalachiteItem::new);
		MALACHITE_ORE = block(RdModBlocks.MALACHITE_ORE);
		MALACHITE_BLOCK = block(RdModBlocks.MALACHITE_BLOCK);
		LOW_MYCELIUM = block(RdModBlocks.LOW_MYCELIUM);
		DEEPSLATE_LACE_AGATE_ORE = block(RdModBlocks.DEEPSLATE_LACE_AGATE_ORE);
		LOW_LACE_AGATE_ORE = block(RdModBlocks.LOW_LACE_AGATE_ORE);
		DEEPSLATE_MALACHITE_ORE = block(RdModBlocks.DEEPSLATE_MALACHITE_ORE);
		LOW_MALACHITE_ORE = block(RdModBlocks.LOW_MALACHITE_ORE);
		DEEPSLATE_PYRITE_ORE = block(RdModBlocks.DEEPSLATE_PYRITE_ORE);
		LOW_PYRITE_ORE = block(RdModBlocks.LOW_PYRITE_ORE);
		DEEPSLATE_CLINOHUMITE_ORE = block(RdModBlocks.DEEPSLATE_CLINOHUMITE_ORE);
		LOW_CLINOHUMITE_ORE = block(RdModBlocks.LOW_CLINOHUMITE_ORE);
		PETRIFIED_WOOD = block(RdModBlocks.PETRIFIED_WOOD);
		ESSENCE_TRANSFORMER = block(RdModBlocks.ESSENCE_TRANSFORMER);
		SPRUCE_PILLAR = block(RdModBlocks.SPRUCE_PILLAR);
		BIRCH_PILLAR = block(RdModBlocks.BIRCH_PILLAR);
		JUNGLE_PILLAR = block(RdModBlocks.JUNGLE_PILLAR);
		ACACIA_PILLAR = block(RdModBlocks.ACACIA_PILLAR);
		DARK_OAK_PILLAR = block(RdModBlocks.DARK_OAK_PILLAR);
		CRIMSON_PILLAR = block(RdModBlocks.CRIMSON_PILLAR);
		WARPED_PILLAR = block(RdModBlocks.WARPED_PILLAR);
		FLAMEWOOD_PILLAR = block(RdModBlocks.FLAMEWOOD_PILLAR, new Item.Properties().fireResistant());
		CACTUS_SWORD = REGISTRY.register("cactus_sword", CactusSwordItem::new);
		CACTUS_PLANKS = block(RdModBlocks.CACTUS_PLANKS);
		CACTUS_STAIRS = block(RdModBlocks.CACTUS_STAIRS);
		CACTUS_SLAB = block(RdModBlocks.CACTUS_SLAB);
		CACTUS_FENCE = block(RdModBlocks.CACTUS_FENCE);
		CACTUS_FENCE_GATE = block(RdModBlocks.CACTUS_FENCE_GATE);
		CACTUS_PRESSURE_PLATE = block(RdModBlocks.CACTUS_PRESSURE_PLATE);
		CACTUS_BUTTON = block(RdModBlocks.CACTUS_BUTTON);
		HARDENED_CACTUS_STEM = block(RdModBlocks.HARDENED_CACTUS_STEM);
		HARDENED_CACTUS_ARM = block(RdModBlocks.HARDENED_CACTUS_ARM);
		COPPER_NUGGET = REGISTRY.register("copper_nugget", CopperNuggetItem::new);
		COPPER_SWORD = REGISTRY.register("copper_sword", CopperSwordItem::new);
		COPPER_AXE = REGISTRY.register("copper_axe", CopperAxeItem::new);
		COPPER_PICKAXE = REGISTRY.register("copper_pickaxe", CopperPickaxeItem::new);
		COPPER_SHOVEL = REGISTRY.register("copper_shovel", CopperShovelItem::new);
		COPPER_HOE = REGISTRY.register("copper_hoe", CopperHoeItem::new);
		LOW_LILY = block(RdModBlocks.LOW_LILY);
		GREENSTONE_BRICK = block(RdModBlocks.GREENSTONE_BRICK);
		CHERRY_PILLAR = block(RdModBlocks.CHERRY_PILLAR);
		WATER_LILY = block(RdModBlocks.WATER_LILY);
		COPPER_HELMET = REGISTRY.register("copper_helmet", CopperItem.Helmet::new);
		COPPER_CHESTPLATE = REGISTRY.register("copper_chestplate", CopperItem.Chestplate::new);
		COPPER_LEGGINGS = REGISTRY.register("copper_leggings", CopperItem.Leggings::new);
		COPPER_BOOTS = REGISTRY.register("copper_boots", CopperItem.Boots::new);
		FRYSHROOM = REGISTRY.register("fryshroom", FryshroomItem::new);
		DEBUG = block(RdModBlocks.DEBUG);
		APPLE_PIE = REGISTRY.register("apple_pie", ApplePieItem::new);
		BAMBOO_PILLAR = block(RdModBlocks.BAMBOO_PILLAR);
		ICE_DOOR = doubleBlock(RdModBlocks.ICE_DOOR);
		FREEZER = block(RdModBlocks.FREEZER);
		RAW_FLESH = REGISTRY.register("raw_flesh", FleshItem::new);
		COOKED_FLESH = REGISTRY.register("cooked_flesh", CookedFleshItem::new);
		MUSHROOM_PLANKS = block(RdModBlocks.MUSHROOM_PLANKS);
		MUSHROOM_STAIRS = block(RdModBlocks.MUSHROOM_STAIRS);
		MUSHROOM_SLAB = block(RdModBlocks.MUSHROOM_SLAB);
		MUSHROOM_FENCE = block(RdModBlocks.MUSHROOM_FENCE);
		MUSHROOM_FENCE_GATE = block(RdModBlocks.MUSHROOM_FENCE_GATE);
		MUSHROOM_PRESSURE_PLATE = block(RdModBlocks.MUSHROOM_PRESSURE_PLATE);
		MUSHROOM_BUTTON = block(RdModBlocks.MUSHROOM_BUTTON);
		SUGAR_COOKIE = REGISTRY.register("sugar_cookie", SugarCookieItem::new);
		STRIPPED_MYCON_STEM = block(RdModBlocks.STRIPPED_MYCON_STEM);
		STRIPPED_MYCON_HYPHAE = block(RdModBlocks.STRIPPED_MYCON_HYPHAE);
		FAKE_DIRT = block(RdModBlocks.FAKE_DIRT);
		FAKE_GRASS = block(RdModBlocks.FAKE_GRASS);
		HIGHWOOD_LOG = block(RdModBlocks.HIGHWOOD_LOG);
		HIGHWOOD_WOOD = block(RdModBlocks.HIGHWOOD_WOOD);
		STRIPPED_HIGHWOOD_LOG = block(RdModBlocks.STRIPPED_HIGHWOOD_LOG);
		STRIPPED_HIGHWOOD_WOOD = block(RdModBlocks.STRIPPED_HIGHWOOD_WOOD);
		HIGHWOOD_PLANKS = block(RdModBlocks.HIGHWOOD_PLANKS);
		HIGHWOOD_LEAVES = block(RdModBlocks.HIGHWOOD_LEAVES);
		HIGHWOOD_STAIRS = block(RdModBlocks.HIGHWOOD_STAIRS);
		HIGHWOOD_SLAB = block(RdModBlocks.HIGHWOOD_SLAB);
		HIGHWOOD_FENCE = block(RdModBlocks.HIGHWOOD_FENCE);
		HIGHWOOD_FENCE_GATE = block(RdModBlocks.HIGHWOOD_FENCE_GATE);
		HIGHWOOD_DOOR = doubleBlock(RdModBlocks.HIGHWOOD_DOOR);
		HIGHWOOD_TRAPDOOR = block(RdModBlocks.HIGHWOOD_TRAPDOOR);
		HIGHWOOD_PRESSURE_PLATE = block(RdModBlocks.HIGHWOOD_PRESSURE_PLATE);
		HIGHWOOD_BUTTON = block(RdModBlocks.HIGHWOOD_BUTTON);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return doubleBlock(block, new Item.Properties());
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), properties));
	}
}