/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.fauxjang.rubylands.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.client.event.RegisterColorHandlersEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import com.fauxjang.rubylands.block.*;
import com.fauxjang.rubylands.RdMod;

public class RdModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(RdMod.MODID);
	public static final DeferredBlock<Block> OAK_PILLAR;
	public static final DeferredBlock<Block> ESSENCE_CACHE;
	public static final DeferredBlock<Block> WINDOW;
	public static final DeferredBlock<Block> IRON_BRICK;
	public static final DeferredBlock<Block> GOLD_BRICK;
	public static final DeferredBlock<Block> DIAMOND_BRICK;
	public static final DeferredBlock<Block> OBSIDIAN_BRICK;
	public static final DeferredBlock<Block> STONE_SCAFFOLD;
	public static final DeferredBlock<Block> XRAY_SCAFFOLD;
	public static final DeferredBlock<Block> SCAFFOLD;
	public static final DeferredBlock<Block> BLUE_DIMENSION_TILE;
	public static final DeferredBlock<Block> YELLOW_DIMENSION_TILE;
	public static final DeferredBlock<Block> DIMENSION_FLOOR;
	public static final DeferredBlock<Block> BLUE_FIRE_IDK;
	public static final DeferredBlock<Block> FLAME_INFUSED_LILY;
	public static final DeferredBlock<Block> GOLD_INFUSED_LILY;
	public static final DeferredBlock<Block> OBSIDIAN_INFUSED_LILY;
	public static final DeferredBlock<Block> SALT_BLOCK;
	public static final DeferredBlock<Block> DIMENSION_WALL;
	public static final DeferredBlock<Block> CYAN_MOJANG_BLOCK;
	public static final DeferredBlock<Block> WHITE_MOJANG_BLOCK;
	public static final DeferredBlock<Block> GREEN_MOJANG_BLOCK;
	public static final DeferredBlock<Block> FLAMEWOOD_WOOD;
	public static final DeferredBlock<Block> FLAMEWOOD_LOG;
	public static final DeferredBlock<Block> FLAMEWOOD_PLANKS;
	public static final DeferredBlock<Block> FLAMEWOOD_LEAVES;
	public static final DeferredBlock<Block> FLAMEWOOD_STAIRS;
	public static final DeferredBlock<Block> FLAMEWOOD_SLAB;
	public static final DeferredBlock<Block> FLAMEWOOD_FENCE;
	public static final DeferredBlock<Block> FLAMEWOOD_FENCE_GATE;
	public static final DeferredBlock<Block> FLAMEWOOD_PRESSURE_PLATE;
	public static final DeferredBlock<Block> FLAMEWOOD_BUTTON;
	public static final DeferredBlock<Block> STRIPPED_FLAMEWOOD_LOG;
	public static final DeferredBlock<Block> STRIPPED_FLAMEWOOD_WOOD;
	public static final DeferredBlock<Block> FLAMEWOOD_SAPLING;
	public static final DeferredBlock<Block> HUB_DOOR;
	public static final DeferredBlock<Block> FLAMEWOOD_DOOR;
	public static final DeferredBlock<Block> FLAMEWOOD_TRAPDOOR;
	public static final DeferredBlock<Block> STONE_PATH;
	public static final DeferredBlock<Block> SALT_BRICKS;
	public static final DeferredBlock<Block> SALT_BRICK_SLAB;
	public static final DeferredBlock<Block> SALT_BRICK_STAIRS;
	public static final DeferredBlock<Block> SALT_BRICK_WALL;
	public static final DeferredBlock<Block> TEA_WOOD;
	public static final DeferredBlock<Block> TEA_LOG;
	public static final DeferredBlock<Block> TEA_PLANKS;
	public static final DeferredBlock<Block> TEA_LEAVES;
	public static final DeferredBlock<Block> TEA_STAIRS;
	public static final DeferredBlock<Block> TEA_SLAB;
	public static final DeferredBlock<Block> TEA_FENCE;
	public static final DeferredBlock<Block> TEA_FENCE_GATE;
	public static final DeferredBlock<Block> TEA_PRESSURE_PLATE;
	public static final DeferredBlock<Block> TEA_BUTTON;
	public static final DeferredBlock<Block> TEA_DOOR;
	public static final DeferredBlock<Block> TEA_TRAPDOOR;
	public static final DeferredBlock<Block> STRIPPED_TEA_WOOD;
	public static final DeferredBlock<Block> STRIPPED_TEA_LOG;
	public static final DeferredBlock<Block> TEA_SAPLING;
	public static final DeferredBlock<Block> LOW_STONE;
	public static final DeferredBlock<Block> COBBLED_LOW_STONE;
	public static final DeferredBlock<Block> ELDERSTONE_COAL_ORE;
	public static final DeferredBlock<Block> LOW_STONE_IRON_ORE;
	public static final DeferredBlock<Block> LOW_STONE_GOLD_ORE;
	public static final DeferredBlock<Block> LOW_STONE_DIAMOND_ORE;
	public static final DeferredBlock<Block> MYCON_HYPHAE;
	public static final DeferredBlock<Block> MYCON_STEM;
	public static final DeferredBlock<Block> MYCON_PLANKS;
	public static final DeferredBlock<Block> MYCON_CAP;
	public static final DeferredBlock<Block> MYCON_STAIRS;
	public static final DeferredBlock<Block> MYCON_SLAB;
	public static final DeferredBlock<Block> MYCON_FENCE;
	public static final DeferredBlock<Block> MYCON_FENCE_GATE;
	public static final DeferredBlock<Block> MYCON_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MYCON_BUTTON;
	public static final DeferredBlock<Block> POLISHED_LOW_STONE;
	public static final DeferredBlock<Block> LOW_STONE_BRICKS;
	public static final DeferredBlock<Block> CRACKED_LOW_STONE_BRICKS;
	public static final DeferredBlock<Block> PYRITE_ORE;
	public static final DeferredBlock<Block> PYRITE_BLOCK;
	public static final DeferredBlock<Block> CLINOHUMITE_ORE;
	public static final DeferredBlock<Block> CLINOHUMITE_BLOCK;
	public static final DeferredBlock<Block> LACE_AGATE_ORE;
	public static final DeferredBlock<Block> LACE_AGATE_BLOCK;
	public static final DeferredBlock<Block> MALACHITE_ORE;
	public static final DeferredBlock<Block> MALACHITE_BLOCK;
	public static final DeferredBlock<Block> LOW_MYCELIUM;
	public static final DeferredBlock<Block> DEEPSLATE_LACE_AGATE_ORE;
	public static final DeferredBlock<Block> LOW_LACE_AGATE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_MALACHITE_ORE;
	public static final DeferredBlock<Block> LOW_MALACHITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_PYRITE_ORE;
	public static final DeferredBlock<Block> LOW_PYRITE_ORE;
	public static final DeferredBlock<Block> DEEPSLATE_CLINOHUMITE_ORE;
	public static final DeferredBlock<Block> LOW_CLINOHUMITE_ORE;
	public static final DeferredBlock<Block> PETRIFIED_WOOD;
	public static final DeferredBlock<Block> ESSENCE_TRANSFORMER;
	public static final DeferredBlock<Block> SPRUCE_PILLAR;
	public static final DeferredBlock<Block> BIRCH_PILLAR;
	public static final DeferredBlock<Block> JUNGLE_PILLAR;
	public static final DeferredBlock<Block> ACACIA_PILLAR;
	public static final DeferredBlock<Block> DARK_OAK_PILLAR;
	public static final DeferredBlock<Block> CRIMSON_PILLAR;
	public static final DeferredBlock<Block> WARPED_PILLAR;
	public static final DeferredBlock<Block> FLAMEWOOD_PILLAR;
	public static final DeferredBlock<Block> CACTUS_PLANKS;
	public static final DeferredBlock<Block> CACTUS_STAIRS;
	public static final DeferredBlock<Block> CACTUS_SLAB;
	public static final DeferredBlock<Block> CACTUS_FENCE;
	public static final DeferredBlock<Block> CACTUS_FENCE_GATE;
	public static final DeferredBlock<Block> CACTUS_PRESSURE_PLATE;
	public static final DeferredBlock<Block> CACTUS_BUTTON;
	public static final DeferredBlock<Block> HARDENED_CACTUS_STEM;
	public static final DeferredBlock<Block> HARDENED_CACTUS_ARM;
	public static final DeferredBlock<Block> LOW_LILY;
	public static final DeferredBlock<Block> GREENSTONE_BRICK;
	public static final DeferredBlock<Block> CHERRY_PILLAR;
	public static final DeferredBlock<Block> WATER_LILY;
	public static final DeferredBlock<Block> DEBUG;
	public static final DeferredBlock<Block> BAMBOO_PILLAR;
	public static final DeferredBlock<Block> ICE_DOOR;
	public static final DeferredBlock<Block> FREEZER;
	public static final DeferredBlock<Block> MUSHROOM_PLANKS;
	public static final DeferredBlock<Block> MUSHROOM_STAIRS;
	public static final DeferredBlock<Block> MUSHROOM_SLAB;
	public static final DeferredBlock<Block> MUSHROOM_FENCE;
	public static final DeferredBlock<Block> MUSHROOM_FENCE_GATE;
	public static final DeferredBlock<Block> MUSHROOM_PRESSURE_PLATE;
	public static final DeferredBlock<Block> MUSHROOM_BUTTON;
	public static final DeferredBlock<Block> STRIPPED_MYCON_STEM;
	public static final DeferredBlock<Block> STRIPPED_MYCON_HYPHAE;
	public static final DeferredBlock<Block> FAKE_DIRT;
	public static final DeferredBlock<Block> FAKE_GRASS;
	public static final DeferredBlock<Block> HIGHWOOD_LOG;
	public static final DeferredBlock<Block> HIGHWOOD_WOOD;
	public static final DeferredBlock<Block> STRIPPED_HIGHWOOD_LOG;
	public static final DeferredBlock<Block> STRIPPED_HIGHWOOD_WOOD;
	public static final DeferredBlock<Block> HIGHWOOD_PLANKS;
	public static final DeferredBlock<Block> HIGHWOOD_LEAVES;
	public static final DeferredBlock<Block> HIGHWOOD_STAIRS;
	public static final DeferredBlock<Block> HIGHWOOD_SLAB;
	public static final DeferredBlock<Block> HIGHWOOD_FENCE;
	public static final DeferredBlock<Block> HIGHWOOD_FENCE_GATE;
	public static final DeferredBlock<Block> HIGHWOOD_DOOR;
	public static final DeferredBlock<Block> HIGHWOOD_TRAPDOOR;
	public static final DeferredBlock<Block> HIGHWOOD_PRESSURE_PLATE;
	public static final DeferredBlock<Block> HIGHWOOD_BUTTON;
	static {
		OAK_PILLAR = REGISTRY.register("oak_pillar", WoodenPillarBlock::new);
		ESSENCE_CACHE = REGISTRY.register("essence_cache", EssenceCacheBlock::new);
		WINDOW = REGISTRY.register("window", FortifiedGlassBlock::new);
		IRON_BRICK = REGISTRY.register("iron_brick", IronBrickBlock::new);
		GOLD_BRICK = REGISTRY.register("gold_brick", GoldBrickBlock::new);
		DIAMOND_BRICK = REGISTRY.register("diamond_brick", DiamondBrickBlock::new);
		OBSIDIAN_BRICK = REGISTRY.register("obsidian_brick", ObsidianBrickBlock::new);
		STONE_SCAFFOLD = REGISTRY.register("stone_scaffold", TileBlockBlock::new);
		XRAY_SCAFFOLD = REGISTRY.register("xray_scaffold", TileBlock2Block::new);
		SCAFFOLD = REGISTRY.register("scaffold", TileBlock2NonFuckedBlock::new);
		BLUE_DIMENSION_TILE = REGISTRY.register("blue_dimension_tile", TileBlock3Block::new);
		YELLOW_DIMENSION_TILE = REGISTRY.register("yellow_dimension_tile", TileBlock4Block::new);
		DIMENSION_FLOOR = REGISTRY.register("dimension_floor", DimensionFloorBlockBlock::new);
		BLUE_FIRE_IDK = REGISTRY.register("blue_fire_idk", BlueFireIdkBlock::new);
		FLAME_INFUSED_LILY = REGISTRY.register("flame_infused_lily", GlowingFlowerInfBasicBlock::new);
		GOLD_INFUSED_LILY = REGISTRY.register("gold_infused_lily", GoldenFlowerInfGoldBlock::new);
		OBSIDIAN_INFUSED_LILY = REGISTRY.register("obsidian_infused_lily", GlowingFlowerInfObsidianBlock::new);
		SALT_BLOCK = REGISTRY.register("salt_block", SaltBlockBlock::new);
		DIMENSION_WALL = REGISTRY.register("dimension_wall", DimensionWallBlockBlock::new);
		CYAN_MOJANG_BLOCK = REGISTRY.register("cyan_mojang_block", AltMojangHypostasisAnemoBlock::new);
		WHITE_MOJANG_BLOCK = REGISTRY.register("white_mojang_block", Imgur9F0A3unBlock::new);
		GREEN_MOJANG_BLOCK = REGISTRY.register("green_mojang_block", YeahWeHadFunWithThisAsYouCanSeeBlock::new);
		FLAMEWOOD_WOOD = REGISTRY.register("flamewood_wood", FlamewoodWoodBlock::new);
		FLAMEWOOD_LOG = REGISTRY.register("flamewood_log", FlamewoodLogBlock::new);
		FLAMEWOOD_PLANKS = REGISTRY.register("flamewood_planks", FlamewoodPlanksBlock::new);
		FLAMEWOOD_LEAVES = REGISTRY.register("flamewood_leaves", FlamewoodLeavesBlock::new);
		FLAMEWOOD_STAIRS = REGISTRY.register("flamewood_stairs", FlamewoodStairsBlock::new);
		FLAMEWOOD_SLAB = REGISTRY.register("flamewood_slab", FlamewoodSlabBlock::new);
		FLAMEWOOD_FENCE = REGISTRY.register("flamewood_fence", FlamewoodFenceBlock::new);
		FLAMEWOOD_FENCE_GATE = REGISTRY.register("flamewood_fence_gate", FlamewoodFenceGateBlock::new);
		FLAMEWOOD_PRESSURE_PLATE = REGISTRY.register("flamewood_pressure_plate", FlamewoodPressurePlateBlock::new);
		FLAMEWOOD_BUTTON = REGISTRY.register("flamewood_button", FlamewoodButtonBlock::new);
		STRIPPED_FLAMEWOOD_LOG = REGISTRY.register("stripped_flamewood_log", StrippedFlamewoodLogBlock::new);
		STRIPPED_FLAMEWOOD_WOOD = REGISTRY.register("stripped_flamewood_wood", StrippedFlamewoodWoodBlock::new);
		FLAMEWOOD_SAPLING = REGISTRY.register("flamewood_sapling", FlamewoodSaplingBlock::new);
		HUB_DOOR = REGISTRY.register("hub_door", HubDoorBlock::new);
		FLAMEWOOD_DOOR = REGISTRY.register("flamewood_door", FlamewoodDoorBlock::new);
		FLAMEWOOD_TRAPDOOR = REGISTRY.register("flamewood_trapdoor", FlamewoodTrapdoorBlock::new);
		STONE_PATH = REGISTRY.register("stone_path", StonePathBlock::new);
		SALT_BRICKS = REGISTRY.register("salt_bricks", SaltBricksBlock::new);
		SALT_BRICK_SLAB = REGISTRY.register("salt_brick_slab", SaltBricksSlabBlock::new);
		SALT_BRICK_STAIRS = REGISTRY.register("salt_brick_stairs", SaltBricksStairsBlock::new);
		SALT_BRICK_WALL = REGISTRY.register("salt_brick_wall", SaltBricksWallBlock::new);
		TEA_WOOD = REGISTRY.register("tea_wood", TeaWoodBlock::new);
		TEA_LOG = REGISTRY.register("tea_log", TeaLogBlock::new);
		TEA_PLANKS = REGISTRY.register("tea_planks", TeaPlanksBlock::new);
		TEA_LEAVES = REGISTRY.register("tea_leaves", TeaLeavesBlock::new);
		TEA_STAIRS = REGISTRY.register("tea_stairs", TeaStairsBlock::new);
		TEA_SLAB = REGISTRY.register("tea_slab", TeaSlabBlock::new);
		TEA_FENCE = REGISTRY.register("tea_fence", TeaFenceBlock::new);
		TEA_FENCE_GATE = REGISTRY.register("tea_fence_gate", TeaFenceGateBlock::new);
		TEA_PRESSURE_PLATE = REGISTRY.register("tea_pressure_plate", TeaPressurePlateBlock::new);
		TEA_BUTTON = REGISTRY.register("tea_button", TeaButtonBlock::new);
		TEA_DOOR = REGISTRY.register("tea_door", TeaDoorBlock::new);
		TEA_TRAPDOOR = REGISTRY.register("tea_trapdoor", TeaTrapdoorBlock::new);
		STRIPPED_TEA_WOOD = REGISTRY.register("stripped_tea_wood", StrippedTeaWoodBlock::new);
		STRIPPED_TEA_LOG = REGISTRY.register("stripped_tea_log", StrippedTeaLogBlock::new);
		TEA_SAPLING = REGISTRY.register("tea_sapling", TeaSaplingBlock::new);
		LOW_STONE = REGISTRY.register("low_stone", LowStoneBlock::new);
		COBBLED_LOW_STONE = REGISTRY.register("cobbled_low_stone", CobbledLowStoneBlock::new);
		ELDERSTONE_COAL_ORE = REGISTRY.register("elderstone_coal_ore", CoalLowStoneOreBlock::new);
		LOW_STONE_IRON_ORE = REGISTRY.register("low_stone_iron_ore", IronLowStoneOreBlock::new);
		LOW_STONE_GOLD_ORE = REGISTRY.register("low_stone_gold_ore", LowStoneGoldOreBlock::new);
		LOW_STONE_DIAMOND_ORE = REGISTRY.register("low_stone_diamond_ore", LowStoneDiamondOreBlock::new);
		MYCON_HYPHAE = REGISTRY.register("mycon_hyphae", MyconWoodBlock::new);
		MYCON_STEM = REGISTRY.register("mycon_stem", MyconLogBlock::new);
		MYCON_PLANKS = REGISTRY.register("mycon_planks", MyconPlanksBlock::new);
		MYCON_CAP = REGISTRY.register("mycon_cap", MyconLeavesBlock::new);
		MYCON_STAIRS = REGISTRY.register("mycon_stairs", MyconStairsBlock::new);
		MYCON_SLAB = REGISTRY.register("mycon_slab", MyconSlabBlock::new);
		MYCON_FENCE = REGISTRY.register("mycon_fence", MyconFenceBlock::new);
		MYCON_FENCE_GATE = REGISTRY.register("mycon_fence_gate", MyconFenceGateBlock::new);
		MYCON_PRESSURE_PLATE = REGISTRY.register("mycon_pressure_plate", MyconPressurePlateBlock::new);
		MYCON_BUTTON = REGISTRY.register("mycon_button", MyconButtonBlock::new);
		POLISHED_LOW_STONE = REGISTRY.register("polished_low_stone", PolishedLowStoneBlock::new);
		LOW_STONE_BRICKS = REGISTRY.register("low_stone_bricks", LowStoneBricksBlock::new);
		CRACKED_LOW_STONE_BRICKS = REGISTRY.register("cracked_low_stone_bricks", CrackedLowStoneBricksBlock::new);
		PYRITE_ORE = REGISTRY.register("pyrite_ore", PyriteOreBlock::new);
		PYRITE_BLOCK = REGISTRY.register("pyrite_block", PyriteBlockBlock::new);
		CLINOHUMITE_ORE = REGISTRY.register("clinohumite_ore", ClinohumiteOreBlock::new);
		CLINOHUMITE_BLOCK = REGISTRY.register("clinohumite_block", ClinohumiteBlockBlock::new);
		LACE_AGATE_ORE = REGISTRY.register("lace_agate_ore", LaceAgateOreBlock::new);
		LACE_AGATE_BLOCK = REGISTRY.register("lace_agate_block", LaceAgateBlockBlock::new);
		MALACHITE_ORE = REGISTRY.register("malachite_ore", MalachiteOreBlock::new);
		MALACHITE_BLOCK = REGISTRY.register("malachite_block", MalachiteBlockBlock::new);
		LOW_MYCELIUM = REGISTRY.register("low_mycelium", ElderMyceliumBlock::new);
		DEEPSLATE_LACE_AGATE_ORE = REGISTRY.register("deepslate_lace_agate_ore", DeepslateLaceAgateOreBlock::new);
		LOW_LACE_AGATE_ORE = REGISTRY.register("low_lace_agate_ore", LowStoneLaceAgateOreBlock::new);
		DEEPSLATE_MALACHITE_ORE = REGISTRY.register("deepslate_malachite_ore", DeepslateMalachiteOreBlock::new);
		LOW_MALACHITE_ORE = REGISTRY.register("low_malachite_ore", LowStoneMalachiteOreBlock::new);
		DEEPSLATE_PYRITE_ORE = REGISTRY.register("deepslate_pyrite_ore", DeepslatePyriteOreBlock::new);
		LOW_PYRITE_ORE = REGISTRY.register("low_pyrite_ore", LowPyriteOreBlock::new);
		DEEPSLATE_CLINOHUMITE_ORE = REGISTRY.register("deepslate_clinohumite_ore", DeepslateClinohumiteOreBlock::new);
		LOW_CLINOHUMITE_ORE = REGISTRY.register("low_clinohumite_ore", LowClinohumiteOreBlock::new);
		PETRIFIED_WOOD = REGISTRY.register("petrified_wood", PetrifiedWoodBlock::new);
		ESSENCE_TRANSFORMER = REGISTRY.register("essence_transformer", EssenceTransformerBlock::new);
		SPRUCE_PILLAR = REGISTRY.register("spruce_pillar", SprucePillarBlock::new);
		BIRCH_PILLAR = REGISTRY.register("birch_pillar", BirchPillarBlock::new);
		JUNGLE_PILLAR = REGISTRY.register("jungle_pillar", JunglePillarBlock::new);
		ACACIA_PILLAR = REGISTRY.register("acacia_pillar", AcaciaPillarBlock::new);
		DARK_OAK_PILLAR = REGISTRY.register("dark_oak_pillar", DarkOakPillarBlock::new);
		CRIMSON_PILLAR = REGISTRY.register("crimson_pillar", CrimsonPillarBlock::new);
		WARPED_PILLAR = REGISTRY.register("warped_pillar", WarpedPillarBlock::new);
		FLAMEWOOD_PILLAR = REGISTRY.register("flamewood_pillar", FlamewoodPillarBlock::new);
		CACTUS_PLANKS = REGISTRY.register("cactus_planks", CactusPlanksBlock::new);
		CACTUS_STAIRS = REGISTRY.register("cactus_stairs", CactusStairsBlock::new);
		CACTUS_SLAB = REGISTRY.register("cactus_slab", CactusSlabBlock::new);
		CACTUS_FENCE = REGISTRY.register("cactus_fence", CactusFenceBlock::new);
		CACTUS_FENCE_GATE = REGISTRY.register("cactus_fence_gate", CactusFenceGateBlock::new);
		CACTUS_PRESSURE_PLATE = REGISTRY.register("cactus_pressure_plate", CactusPressurePlateBlock::new);
		CACTUS_BUTTON = REGISTRY.register("cactus_button", CactusButtonBlock::new);
		HARDENED_CACTUS_STEM = REGISTRY.register("hardened_cactus_stem", HardenedCactusStemBlock::new);
		HARDENED_CACTUS_ARM = REGISTRY.register("hardened_cactus_arm", HardenedCactusArmBlock::new);
		LOW_LILY = REGISTRY.register("low_lily", ElderLilyBlock::new);
		GREENSTONE_BRICK = REGISTRY.register("greenstone_brick", GreenstoneBrickBlock::new);
		CHERRY_PILLAR = REGISTRY.register("cherry_pillar", CherryPillarBlock::new);
		WATER_LILY = REGISTRY.register("water_lily", GlowingFlowerBlock::new);
		DEBUG = REGISTRY.register("debug", DebugBlock::new);
		BAMBOO_PILLAR = REGISTRY.register("bamboo_pillar", BambooPillarBlock::new);
		ICE_DOOR = REGISTRY.register("ice_door", IceDoorBlock::new);
		FREEZER = REGISTRY.register("freezer", FreezerBlock::new);
		MUSHROOM_PLANKS = REGISTRY.register("mushroom_planks", MushroomPlanksBlock::new);
		MUSHROOM_STAIRS = REGISTRY.register("mushroom_stairs", MushroomStairsBlock::new);
		MUSHROOM_SLAB = REGISTRY.register("mushroom_slab", MushroomSlabBlock::new);
		MUSHROOM_FENCE = REGISTRY.register("mushroom_fence", MushroomFenceBlock::new);
		MUSHROOM_FENCE_GATE = REGISTRY.register("mushroom_fence_gate", MushroomFenceGateBlock::new);
		MUSHROOM_PRESSURE_PLATE = REGISTRY.register("mushroom_pressure_plate", MushroomPressurePlateBlock::new);
		MUSHROOM_BUTTON = REGISTRY.register("mushroom_button", MushroomButtonBlock::new);
		STRIPPED_MYCON_STEM = REGISTRY.register("stripped_mycon_stem", StrippedMyconLogBlock::new);
		STRIPPED_MYCON_HYPHAE = REGISTRY.register("stripped_mycon_hyphae", StrippedMyconWoodBlock::new);
		FAKE_DIRT = REGISTRY.register("fake_dirt", FakeDirtBlock::new);
		FAKE_GRASS = REGISTRY.register("fake_grass", FakeGrassBlock::new);
		HIGHWOOD_LOG = REGISTRY.register("highwood_log", HighwoodLogBlock::new);
		HIGHWOOD_WOOD = REGISTRY.register("highwood_wood", HighwoodWoodBlock::new);
		STRIPPED_HIGHWOOD_LOG = REGISTRY.register("stripped_highwood_log", StrippedHighwoodLogBlock::new);
		STRIPPED_HIGHWOOD_WOOD = REGISTRY.register("stripped_highwood_wood", StrippedHighwoodWoodBlock::new);
		HIGHWOOD_PLANKS = REGISTRY.register("highwood_planks", HighwoodPlanksBlock::new);
		HIGHWOOD_LEAVES = REGISTRY.register("highwood_leaves", HighwoodLeavesBlock::new);
		HIGHWOOD_STAIRS = REGISTRY.register("highwood_stairs", HighwoodStairsBlock::new);
		HIGHWOOD_SLAB = REGISTRY.register("highwood_slab", HighwoodSlabBlock::new);
		HIGHWOOD_FENCE = REGISTRY.register("highwood_fence", HighwoodFenceBlock::new);
		HIGHWOOD_FENCE_GATE = REGISTRY.register("highwood_fence_gate", HighwoodFenceGateBlock::new);
		HIGHWOOD_DOOR = REGISTRY.register("highwood_door", HighwoodDoorBlock::new);
		HIGHWOOD_TRAPDOOR = REGISTRY.register("highwood_trapdoor", HighwoodTrapdoorBlock::new);
		HIGHWOOD_PRESSURE_PLATE = REGISTRY.register("highwood_pressure_plate", HighwoodPressurePlateBlock::new);
		HIGHWOOD_BUTTON = REGISTRY.register("highwood_button", HighwoodButtonBlock::new);
	}

	// Start of user code block custom blocks
	// End of user code block custom blocks
	@EventBusSubscriber(Dist.CLIENT)
	public static class BlocksClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			StonePathBlock.blockColorLoad(event);
			TeaLeavesBlock.blockColorLoad(event);
		}
	}
}